---
name: Robot Framework Tests
on:
  push:
    branches:
      - main
  pull_request: null
jobs:
  robot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-jsonlibrary
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run Robot Framework tests
        run: |
          robot tests/
      - name: Upload Robot Framework reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-reports
          path: |
            output.xml
            report.html
            log.html
